// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: sensecap

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void up_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_screen_time
void ui_screen_time_screen_init(void);
void ui_event_screen_time( lv_event_t * e);
lv_obj_t *ui_screen_time;
void ui_event_wifi__st_button_1( lv_event_t * e);
lv_obj_t *ui_wifi__st_button_1;
lv_obj_t *ui_wifi_st_1;
lv_obj_t *ui_time1;
lv_obj_t *ui_date_panel;
lv_obj_t *ui_date;
lv_obj_t *ui_location;
lv_obj_t *ui_location_Icon;
lv_obj_t *ui_city;
lv_obj_t *ui_sensor_temp;
lv_obj_t *ui_temp_icon_1;
lv_obj_t *ui_temp_title_1;
lv_obj_t *ui_temp_unit_1;
lv_obj_t *ui_temp_data_1;
lv_obj_t *ui_sensor_humidity;
lv_obj_t *ui_humidity_icon_1;
lv_obj_t *ui_humidity_title_1;
lv_obj_t *ui_humidity_unit_1;
lv_obj_t *ui_humidity_data_1;
lv_obj_t *ui_scrolldots1;
lv_obj_t *ui_scrolldots11;
lv_obj_t *ui_scrolldots12;
lv_obj_t *ui_scrolldots13;


// SCREEN: ui_screen_sensor
void ui_screen_sensor_screen_init(void);
void ui_event_screen_sensor( lv_event_t * e);
lv_obj_t *ui_screen_sensor;
void ui_event_wifi__st_button_2( lv_event_t * e);
lv_obj_t *ui_wifi__st_button_2;
lv_obj_t *ui_wifi_st_2;
lv_obj_t *ui_time2;
lv_obj_t *ui_co2;
lv_obj_t *ui_co2_icon;
lv_obj_t *ui_co2_title;
lv_obj_t *ui_co2_data;
lv_obj_t *ui_co2_unit;
lv_obj_t *ui_tvoc_2;
lv_obj_t *ui_tvoc_icon_2;
lv_obj_t *ui_tvoc_title_2;
lv_obj_t *ui_tvoc_data;
lv_obj_t *ui_tvoc_unit_2;
lv_obj_t *ui_temp2;
lv_obj_t *ui_temp_icon_2;
lv_obj_t *ui_temp_title_2;
lv_obj_t *ui_temp_data_2;
lv_obj_t *ui_temp_unit_2;
lv_obj_t *ui_humidity2;
lv_obj_t *ui_humidity_icon_2;
lv_obj_t *ui_humidity_title_2;
lv_obj_t *ui_humidity_data_2;
lv_obj_t *ui_humidity_unit_2;
lv_obj_t *ui_scrolldots2;
lv_obj_t *ui_scrolldots21;
lv_obj_t *ui_scrolldots22;
lv_obj_t *ui_scrolldots23;


// SCREEN: ui_screen_setting
void ui_screen_setting_screen_init(void);
void ui_event_screen_setting( lv_event_t * e);
lv_obj_t *ui_screen_setting;
void ui_event_wifi__st_button_3( lv_event_t * e);
lv_obj_t *ui_wifi__st_button_3;
lv_obj_t *ui_wifi_st_3;
lv_obj_t *ui_time3;
lv_obj_t *ui_setting_icon;
lv_obj_t *ui_setting_title;
void ui_event_setting_wifi( lv_event_t * e);
lv_obj_t *ui_setting_wifi;
lv_obj_t *ui_setting_wifi_icon;
lv_obj_t *ui_setting_wifi_title;
void ui_event_setting_display( lv_event_t * e);
lv_obj_t *ui_setting_display;
lv_obj_t *ui_setting_display_icon;
lv_obj_t *ui_setting_display_title;
void ui_event_setting_time( lv_event_t * e);
lv_obj_t *ui_setting_time;
lv_obj_t *ui_setting_time_icon;
lv_obj_t *ui_setting_time_title;
lv_obj_t *ui_scrolldots3;
lv_obj_t *ui_scrolldots31;
lv_obj_t *ui_scrolldots32;
lv_obj_t *ui_scrolldots33;
void ui_event_btn_setting_binding( lv_event_t * e);
lv_obj_t *ui_btn_setting_binding;
lv_obj_t *ui_setting_binding_icon;
lv_obj_t *ui_setting_binding_title;
void ui_event_btn_setting_bind( lv_event_t * e);
lv_obj_t *ui_btn_setting_bind;
lv_obj_t *ui_setting_bind_icon;
lv_obj_t *ui_setting_bind_title;


// SCREEN: ui_screen_binding
void ui_screen_binding_screen_init(void);
void ui_event_screen_binding( lv_event_t * e);
lv_obj_t *ui_screen_binding;
void ui_event_btn_bind_back_setting( lv_event_t * e);
lv_obj_t *ui_btn_bind_back_setting;
lv_obj_t *ui_time5;
void ui_event_wifi__st_button_4( lv_event_t * e);
lv_obj_t *ui_wifi__st_button_4;
lv_obj_t *ui_wifi_st_7;
lv_obj_t *ui_time4;
lv_obj_t *ui_scrolldots4;
lv_obj_t *ui_scrolldots5;
lv_obj_t *ui_scrolldots6;
lv_obj_t *ui_scrolldots7;
lv_obj_t *ui_Panel_user;
lv_obj_t *ui_Panel_SN;
lv_obj_t *ui_Label_SN;
lv_obj_t *ui_TextArea_WAD;
lv_obj_t *ui_Label_WAD;
lv_obj_t *ui_TextArea_SN;
void ui_event_btn_bind( lv_event_t * e);
lv_obj_t *ui_btn_bind;
lv_obj_t *ui_label_bind;


// SCREEN: ui_screen_wifi
void ui_screen_wifi_screen_init(void);
lv_obj_t *ui_screen_wifi;
lv_obj_t *ui_wifi_st_6;
lv_obj_t *ui_wifi_title;
void ui_event_back3( lv_event_t * e);
lv_obj_t *ui_back3;


// SCREEN: ui_screen_display
void ui_screen_display_screen_init(void);
lv_obj_t *ui_screen_display;
lv_obj_t *ui_wifi_st_4;
void ui_event_back1( lv_event_t * e);
lv_obj_t *ui_back1;
lv_obj_t *ui_display_title;
lv_obj_t *ui_brighness;
lv_obj_t *ui_brighness_cfg;
lv_obj_t *ui_brighness_title;
lv_obj_t *ui_brighness_icon_1;
lv_obj_t *ui_brighness_icon_2;
lv_obj_t *ui_sleep_mode;
lv_obj_t *ui_sleep_mode_title;
void ui_event_sleep_mode_cfg( lv_event_t * e);
lv_obj_t *ui_sleep_mode_cfg;
lv_obj_t *ui_sleep_mode_time;
lv_obj_t *ui_after;
void ui_event_sleep_mode_time_cfg( lv_event_t * e);
lv_obj_t *ui_sleep_mode_time_cfg;
lv_obj_t *ui_display_min;
void ui_event_display_keyboard( lv_event_t * e);
lv_obj_t *ui_display_keyboard;


// SCREEN: ui_screen_date_time
void ui_screen_date_time_screen_init(void);
lv_obj_t *ui_screen_date_time;
lv_obj_t *ui_wifi_st_5;
void ui_event_back2( lv_event_t * e);
lv_obj_t *ui_back2;
lv_obj_t *ui_date_time_title;
lv_obj_t *ui_time_format;
lv_obj_t *ui_time_format_title;
lv_obj_t *ui_time_format_cfg;
lv_obj_t *ui_auto_update;
lv_obj_t *ui_auto_update_title;
void ui_event_auto_update_cfg( lv_event_t * e);
lv_obj_t *ui_auto_update_cfg;
lv_obj_t *ui_date_time;
lv_obj_t *ui_time_zone_title;
lv_obj_t *ui_time_zone_num_cfg;
lv_obj_t *ui_utc_tile;
lv_obj_t *ui_time_zone_sign_cfg_;
lv_obj_t *ui_daylight_title;
lv_obj_t *ui_daylight_cfg;
lv_obj_t *ui_manual_setting_title;
lv_obj_t *ui_date_cfg;
lv_obj_t *ui_hour_cfg;
lv_obj_t *ui_min_cfg;
lv_obj_t *ui_sec_cfg;
lv_obj_t *ui_time_label1;
lv_obj_t *ui_time_label2;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_co[1] = {&ui_img_co2_png};
const lv_img_dsc_t *ui_imgset_humidity_[2] = {&ui_img_humidity_1_png, &ui_img_humidity_2_png};
const lv_img_dsc_t *ui_imgset_location[1] = {&ui_img_location2_png};
const lv_img_dsc_t *ui_imgset_temp_[2] = {&ui_img_temp_1_png, &ui_img_temp_2_png};
const lv_img_dsc_t *ui_imgset_wifi_[3] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void up_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -50, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 100);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_screen_time( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_sensor, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screen_sensor_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_wifi__st_button_1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
}
}
void ui_event_screen_sensor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screen_setting_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_time, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screen_time_screen_init);
}
}
void ui_event_wifi__st_button_2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
}
}
void ui_event_screen_setting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_time, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screen_time_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_screen_sensor, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screen_sensor_screen_init);
}
}
void ui_event_wifi__st_button_3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
}
}
void ui_event_setting_wifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
}
}
void ui_event_setting_display( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_screen_display, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_display_screen_init);
}
}
void ui_event_setting_time( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_screen_date_time, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_date_time_screen_init);
}
}
void ui_event_btn_setting_binding( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_binding, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen_binding_screen_init);
}
}
void ui_event_btn_setting_bind( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_screen_binding, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen_binding_screen_init);
}
}
void ui_event_screen_binding( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_btn_bind_back_setting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_wifi__st_button_4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
}
}
void ui_event_btn_bind( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      fn_bind_confirm( e );
}
}
void ui_event_back3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_back1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_sleep_mode_cfg( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_display_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_sleep_mode_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_sleep_mode_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_sleep_mode_time_cfg( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_display_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_display_keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_display_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CANCEL) {
      _ui_flag_modify( ui_display_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_display_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_back2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screen_setting, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_screen_setting_screen_init);
}
}
void ui_event_auto_update_cfg( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_date_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_date_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screen_time_screen_init();
ui_screen_sensor_screen_init();
ui_screen_setting_screen_init();
ui_screen_binding_screen_init();
ui_screen_wifi_screen_init();
ui_screen_display_screen_init();
ui_screen_date_time_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screen_time);
}
