// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sensecap

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btn_register_device_start(lv_event_t * e);
void btn_register_device_exit(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
