// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: sensecap

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fn_iotex_unbind(lv_event_t * e);
void fn_bind_confirm(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
