// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_sensor_screen_init(void)
{
ui_screen_sensor = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_sensor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi__st_button_2 = lv_btn_create(ui_screen_sensor);
lv_obj_set_width( ui_wifi__st_button_2, 60);
lv_obj_set_height( ui_wifi__st_button_2, 60);
lv_obj_set_x( ui_wifi__st_button_2, -10 );
lv_obj_set_y( ui_wifi__st_button_2, 10 );
lv_obj_set_align( ui_wifi__st_button_2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi__st_button_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifi__st_button_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi__st_button_2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi__st_button_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_wifi__st_button_2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wifi_st_2 = lv_img_create(ui_wifi__st_button_2);
lv_img_set_src(ui_wifi_st_2, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifi_st_2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time2 = lv_label_create(ui_screen_sensor);
lv_obj_set_width( ui_time2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time2, 30 );
lv_obj_set_y( ui_time2, 20 );
lv_label_set_text(ui_time2,"21:20");
lv_obj_set_style_text_font(ui_time2, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2 = lv_btn_create(ui_screen_sensor);
lv_obj_set_width( ui_co2, 436);
lv_obj_set_height( ui_co2, 140);
lv_obj_set_x( ui_co2, 0 );
lv_obj_set_y( ui_co2, -100 );
lv_obj_set_align( ui_co2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_co2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_co2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_co2, lv_color_hex(0x529D53), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_co2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_icon = lv_img_create(ui_co2);
lv_img_set_src(ui_co2_icon, &ui_img_co2_png);
lv_obj_set_width( ui_co2_icon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_co2_icon, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_co2_icon, -184 );
lv_obj_set_y( ui_co2_icon, -40 );
lv_obj_set_align( ui_co2_icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_co2_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_co2_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_co2_title = lv_label_create(ui_co2);
lv_obj_set_width( ui_co2_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_co2_title, -134 );
lv_obj_set_y( ui_co2_title, -40 );
lv_obj_set_align( ui_co2_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_co2_title,"CO2");
lv_obj_set_style_text_font(ui_co2_title, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_data = lv_label_create(ui_co2);
lv_obj_set_width( ui_co2_data, 200);
lv_obj_set_height( ui_co2_data, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_co2_data, -90 );
lv_obj_set_y( ui_co2_data, -1 );
lv_obj_set_align( ui_co2_data, LV_ALIGN_CENTER );
lv_label_set_text(ui_co2_data,"-- ");
lv_obj_set_style_text_align(ui_co2_data, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_co2_data, &ui_font_font3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_unit = lv_label_create(ui_co2);
lv_obj_set_width( ui_co2_unit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_unit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_co2_unit, 35 );
lv_obj_set_y( ui_co2_unit, 0 );
lv_obj_set_align( ui_co2_unit, LV_ALIGN_CENTER );
lv_label_set_text(ui_co2_unit,"ppm");
lv_obj_set_style_text_font(ui_co2_unit, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvoc_2 = lv_btn_create(ui_screen_sensor);
lv_obj_set_width( ui_tvoc_2, 140);
lv_obj_set_height( ui_tvoc_2, 200);
lv_obj_set_x( ui_tvoc_2, -148 );
lv_obj_set_y( ui_tvoc_2, 80 );
lv_obj_set_align( ui_tvoc_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tvoc_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_tvoc_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_tvoc_2, lv_color_hex(0xE06D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tvoc_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvoc_icon_2 = lv_img_create(ui_tvoc_2);
lv_img_set_src(ui_tvoc_icon_2, &ui_img_tvoc_png);
lv_obj_set_width( ui_tvoc_icon_2, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_tvoc_icon_2, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_tvoc_icon_2, -40 );
lv_obj_set_y( ui_tvoc_icon_2, -70 );
lv_obj_set_align( ui_tvoc_icon_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tvoc_icon_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_tvoc_icon_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tvoc_title_2 = lv_label_create(ui_tvoc_2);
lv_obj_set_width( ui_tvoc_title_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tvoc_title_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvoc_title_2, 15 );
lv_obj_set_y( ui_tvoc_title_2, -70 );
lv_obj_set_align( ui_tvoc_title_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvoc_title_2,"tVOC");
lv_obj_set_style_text_font(ui_tvoc_title_2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvoc_data = lv_label_create(ui_tvoc_2);
lv_obj_set_width( ui_tvoc_data, 100);
lv_obj_set_height( ui_tvoc_data, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvoc_data, -21 );
lv_obj_set_y( ui_tvoc_data, 0 );
lv_obj_set_align( ui_tvoc_data, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvoc_data,"-- ");
lv_obj_set_style_text_align(ui_tvoc_data, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tvoc_data, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvoc_unit_2 = lv_label_create(ui_tvoc_2);
lv_obj_set_width( ui_tvoc_unit_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tvoc_unit_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvoc_unit_2, 44 );
lv_obj_set_y( ui_tvoc_unit_2, 4 );
lv_obj_set_align( ui_tvoc_unit_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvoc_unit_2,"");
lv_obj_set_style_text_font(ui_tvoc_unit_2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp2 = lv_btn_create(ui_screen_sensor);
lv_obj_set_width( ui_temp2, 140);
lv_obj_set_height( ui_temp2, 200);
lv_obj_set_x( ui_temp2, 0 );
lv_obj_set_y( ui_temp2, 80 );
lv_obj_set_align( ui_temp2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_temp2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_temp2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_temp2, lv_color_hex(0xEEBF41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_icon_2 = lv_img_create(ui_temp2);
lv_img_set_src(ui_temp_icon_2, &ui_img_temp_2_png);
lv_obj_set_width( ui_temp_icon_2, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_temp_icon_2, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_temp_icon_2, -40 );
lv_obj_set_y( ui_temp_icon_2, -70 );
lv_obj_set_align( ui_temp_icon_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_temp_icon_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_temp_icon_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temp_title_2 = lv_label_create(ui_temp2);
lv_obj_set_width( ui_temp_title_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp_title_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_title_2, 15 );
lv_obj_set_y( ui_temp_title_2, -70 );
lv_obj_set_align( ui_temp_title_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_title_2,"Temp");
lv_obj_set_style_text_font(ui_temp_title_2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_data_2 = lv_label_create(ui_temp2);
lv_obj_set_width( ui_temp_data_2, 80);
lv_obj_set_height( ui_temp_data_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_data_2, -20 );
lv_obj_set_y( ui_temp_data_2, 0 );
lv_obj_set_align( ui_temp_data_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_data_2,"-- ");
lv_obj_set_style_text_align(ui_temp_data_2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp_data_2, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_unit_2 = lv_label_create(ui_temp2);
lv_obj_set_width( ui_temp_unit_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp_unit_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp_unit_2, 35 );
lv_obj_set_y( ui_temp_unit_2, 0 );
lv_obj_set_align( ui_temp_unit_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp_unit_2,"C");
lv_obj_set_style_text_font(ui_temp_unit_2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity2 = lv_btn_create(ui_screen_sensor);
lv_obj_set_width( ui_humidity2, 140);
lv_obj_set_height( ui_humidity2, 200);
lv_obj_set_x( ui_humidity2, 148 );
lv_obj_set_y( ui_humidity2, 80 );
lv_obj_set_align( ui_humidity2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_humidity2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_humidity2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_humidity2, lv_color_hex(0x4EACE4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_humidity2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_icon_2 = lv_img_create(ui_humidity2);
lv_img_set_src(ui_humidity_icon_2, &ui_img_humidity_2_png);
lv_obj_set_width( ui_humidity_icon_2, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_humidity_icon_2, LV_SIZE_CONTENT);   /// 53
lv_obj_set_x( ui_humidity_icon_2, -45 );
lv_obj_set_y( ui_humidity_icon_2, -70 );
lv_obj_set_align( ui_humidity_icon_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_humidity_icon_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_humidity_icon_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_humidity_title_2 = lv_label_create(ui_humidity2);
lv_obj_set_width( ui_humidity_title_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity_title_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_title_2, 15 );
lv_obj_set_y( ui_humidity_title_2, -70 );
lv_obj_set_align( ui_humidity_title_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_title_2,"Humidity");
lv_obj_set_style_text_font(ui_humidity_title_2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_data_2 = lv_label_create(ui_humidity2);
lv_obj_set_width( ui_humidity_data_2, 80);
lv_obj_set_height( ui_humidity_data_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_data_2, -30 );
lv_obj_set_y( ui_humidity_data_2, 0 );
lv_obj_set_align( ui_humidity_data_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_data_2,"--");
lv_obj_set_style_text_align(ui_humidity_data_2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humidity_data_2, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_humidity_unit_2 = lv_label_create(ui_humidity2);
lv_obj_set_width( ui_humidity_unit_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humidity_unit_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humidity_unit_2, 25 );
lv_obj_set_y( ui_humidity_unit_2, 0 );
lv_obj_set_align( ui_humidity_unit_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_humidity_unit_2,"%");
lv_obj_set_style_text_font(ui_humidity_unit_2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots2 = lv_obj_create(ui_screen_sensor);
lv_obj_set_width( ui_scrolldots2, 100);
lv_obj_set_height( ui_scrolldots2, 20);
lv_obj_set_x( ui_scrolldots2, 0 );
lv_obj_set_y( ui_scrolldots2, -20 );
lv_obj_set_align( ui_scrolldots2, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_scrolldots2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots21 = lv_obj_create(ui_scrolldots2);
lv_obj_set_width( ui_scrolldots21, 7);
lv_obj_set_height( ui_scrolldots21, 7);
lv_obj_set_align( ui_scrolldots21, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_scrolldots21, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots22 = lv_obj_create(ui_scrolldots2);
lv_obj_set_width( ui_scrolldots22, 7);
lv_obj_set_height( ui_scrolldots22, 7);
lv_obj_set_align( ui_scrolldots22, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_scrolldots22, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots23 = lv_obj_create(ui_scrolldots2);
lv_obj_set_width( ui_scrolldots23, 7);
lv_obj_set_height( ui_scrolldots23, 7);
lv_obj_set_align( ui_scrolldots23, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_scrolldots23, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_wifi__st_button_2, ui_event_wifi__st_button_2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_sensor, ui_event_screen_sensor, LV_EVENT_ALL, NULL);

}
