// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_time_screen_init(void)
{
ui_screen_time = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time_background = lv_img_create(ui_screen_time);
lv_img_set_src(ui_time_background, &ui_img_background_png);
lv_obj_set_width( ui_time_background, lv_pct(100));
lv_obj_set_height( ui_time_background, lv_pct(100));
lv_obj_set_align( ui_time_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_time_background, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_time_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hour1 = lv_obj_create(ui_time_background);
lv_obj_set_width( ui_hour1, 200);
lv_obj_set_height( ui_hour1, 170);
lv_obj_set_x( ui_hour1, -110 );
lv_obj_set_y( ui_hour1, 0 );
lv_obj_set_align( ui_hour1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_hour1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_hour1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hour1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hour_cfg1 = lv_label_create(ui_hour1);
lv_obj_set_width( ui_hour_cfg1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hour_cfg1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_hour_cfg1, LV_ALIGN_CENTER );
lv_label_set_text(ui_hour_cfg1,"20");
lv_obj_set_style_text_font(ui_hour_cfg1, &ui_font_time_font, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_min1 = lv_obj_create(ui_time_background);
lv_obj_set_width( ui_min1, 200);
lv_obj_set_height( ui_min1, 170);
lv_obj_set_x( ui_min1, 110 );
lv_obj_set_y( ui_min1, 0 );
lv_obj_set_align( ui_min1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_min1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_min1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_min1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_min_cfg1 = lv_label_create(ui_min1);
lv_obj_set_width( ui_min_cfg1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_min_cfg1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_min_cfg1, LV_ALIGN_CENTER );
lv_label_set_text(ui_min_cfg1,"23");
lv_obj_set_style_text_font(ui_min_cfg1, &ui_font_time_font, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_min_cfg2 = lv_label_create(ui_min1);
lv_obj_set_width( ui_min_cfg2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_min_cfg2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_min_cfg2, LV_ALIGN_CENTER );
lv_label_set_text(ui_min_cfg2,"23");
lv_obj_set_style_text_font(ui_min_cfg2, &ui_font_time_font, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_location1 = lv_obj_create(ui_time_background);
lv_obj_set_width( ui_location1, 399);
lv_obj_set_height( ui_location1, 30);
lv_obj_set_x( ui_location1, 6 );
lv_obj_set_y( ui_location1, 103 );
lv_obj_set_align( ui_location1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_location1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_location1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_location1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_location1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_location1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_location1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_city = lv_label_create(ui_location1);
lv_obj_set_width( ui_city, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_city, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_city, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_city,"Shen Zhen");
lv_obj_set_style_text_font(ui_city, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_location_Icon1 = lv_img_create(ui_time_background);
lv_img_set_src(ui_location_Icon1, &ui_img_location2_png);
lv_obj_set_width( ui_location_Icon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_location_Icon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_location_Icon1, 199 );
lv_obj_set_y( ui_location_Icon1, 103 );
lv_obj_set_align( ui_location_Icon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_location_Icon1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_location_Icon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_date_panel1 = lv_obj_create(ui_time_background);
lv_obj_set_width( ui_date_panel1, 235);
lv_obj_set_height( ui_date_panel1, 30);
lv_obj_set_x( ui_date_panel1, -103 );
lv_obj_set_y( ui_date_panel1, -108 );
lv_obj_set_align( ui_date_panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_date_panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_date_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_date_panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_date_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_date_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_date_panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_date_panel1);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_date, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_date,"Monday, 22 / 10 /  2023");
lv_label_set_recolor(ui_date,"true");
lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_time_background);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,":");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adorn = lv_obj_create(ui_time_background);
lv_obj_set_width( ui_adorn, 480);
lv_obj_set_height( ui_adorn, 6);
lv_obj_set_align( ui_adorn, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_adorn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_adorn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adorn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_adorn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_adorn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_adorn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi__st_button_1 = lv_btn_create(ui_screen_time);
lv_obj_set_width( ui_wifi__st_button_1, 60);
lv_obj_set_height( ui_wifi__st_button_1, 60);
lv_obj_set_x( ui_wifi__st_button_1, -10 );
lv_obj_set_y( ui_wifi__st_button_1, 10 );
lv_obj_set_align( ui_wifi__st_button_1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi__st_button_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifi__st_button_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi__st_button_1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi__st_button_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_wifi__st_button_1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wifi_st_1 = lv_img_create(ui_wifi__st_button_1);
lv_img_set_src(ui_wifi_st_1, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifi_st_1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots1 = lv_obj_create(ui_screen_time);
lv_obj_set_width( ui_scrolldots1, 100);
lv_obj_set_height( ui_scrolldots1, 20);
lv_obj_set_x( ui_scrolldots1, 0 );
lv_obj_set_y( ui_scrolldots1, -20 );
lv_obj_set_align( ui_scrolldots1, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_scrolldots1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scrolldots1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots11 = lv_obj_create(ui_scrolldots1);
lv_obj_set_width( ui_scrolldots11, 7);
lv_obj_set_height( ui_scrolldots11, 7);
lv_obj_set_align( ui_scrolldots11, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_scrolldots11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots12 = lv_obj_create(ui_scrolldots1);
lv_obj_set_width( ui_scrolldots12, 7);
lv_obj_set_height( ui_scrolldots12, 7);
lv_obj_set_align( ui_scrolldots12, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_scrolldots12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots13 = lv_obj_create(ui_scrolldots1);
lv_obj_set_width( ui_scrolldots13, 7);
lv_obj_set_height( ui_scrolldots13, 7);
lv_obj_set_align( ui_scrolldots13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_scrolldots13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_wifi__st_button_1, ui_event_wifi__st_button_1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_time, ui_event_screen_time, LV_EVENT_ALL, NULL);

}
