// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sensecap

#include "../ui.h"

void ui_screen_wifi_screen_init(void)
{
    ui_screen_wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi_st_6 = lv_img_create(ui_screen_wifi);
    lv_img_set_src(ui_wifi_st_6, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_st_6, -20);
    lv_obj_set_y(ui_wifi_st_6, 20);
    lv_obj_set_align(ui_wifi_st_6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_wifi_st_6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi_title = lv_label_create(ui_screen_wifi);
    lv_obj_set_width(ui_wifi_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_title, 1);
    lv_obj_set_y(ui_wifi_title, 50);
    lv_obj_set_align(ui_wifi_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_wifi_title, "WiFi");
    lv_obj_set_style_text_font(ui_wifi_title, &ui_font_font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back3 = lv_btn_create(ui_screen_wifi);
    lv_obj_set_width(ui_back3, 100);
    lv_obj_set_height(ui_back3, 50);
    lv_obj_set_x(ui_back3, 10);
    lv_obj_set_y(ui_back3, 30);
    lv_obj_add_flag(ui_back3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_back3, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back3, ui_event_back3, LV_EVENT_ALL, NULL);

}
