// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sensecap

#include "../ui.h"

void ui_screen_date_time_screen_init(void)
{
    ui_screen_date_time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_date_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi_st_5 = lv_img_create(ui_screen_date_time);
    lv_img_set_src(ui_wifi_st_5, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_st_5, -20);
    lv_obj_set_y(ui_wifi_st_5, 20);
    lv_obj_set_align(ui_wifi_st_5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_wifi_st_5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back2 = lv_btn_create(ui_screen_date_time);
    lv_obj_set_width(ui_back2, 100);
    lv_obj_set_height(ui_back2, 50);
    lv_obj_set_x(ui_back2, 10);
    lv_obj_set_y(ui_back2, 30);
    lv_obj_add_flag(ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_back2, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_time_title = lv_label_create(ui_screen_date_time);
    lv_obj_set_width(ui_date_time_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date_time_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date_time_title, 0);
    lv_obj_set_y(ui_date_time_title, 50);
    lv_obj_set_align(ui_date_time_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_date_time_title, "Date & Time");
    lv_obj_set_style_text_font(ui_date_time_title, &ui_font_font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_format = lv_obj_create(ui_screen_date_time);
    lv_obj_set_width(ui_time_format, 400);
    lv_obj_set_height(ui_time_format, 50);
    lv_obj_set_x(ui_time_format, 0);
    lv_obj_set_y(ui_time_format, -120);
    lv_obj_set_align(ui_time_format, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time_format, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_format_title = lv_label_create(ui_time_format);
    lv_obj_set_width(ui_time_format_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_format_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_format_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_format_title, "Time Format");

    ui_time_format_cfg = lv_dropdown_create(ui_time_format);
    lv_dropdown_set_options(ui_time_format_cfg, "24H\n12H");
    lv_obj_set_width(ui_time_format_cfg, 100);
    lv_obj_set_height(ui_time_format_cfg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_format_cfg, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_time_format_cfg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_time_format_cfg, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_format_cfg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_auto_update = lv_obj_create(ui_screen_date_time);
    lv_obj_set_width(ui_auto_update, 400);
    lv_obj_set_height(ui_auto_update, 50);
    lv_obj_set_x(ui_auto_update, 0);
    lv_obj_set_y(ui_auto_update, -60);
    lv_obj_set_align(ui_auto_update, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_auto_update, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_auto_update, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_auto_update_title = lv_label_create(ui_auto_update);
    lv_obj_set_width(ui_auto_update_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auto_update_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_auto_update_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_auto_update_title, "Auto Update");

    ui_auto_update_cfg = lv_switch_create(ui_auto_update);
    lv_obj_set_width(ui_auto_update_cfg, 50);
    lv_obj_set_height(ui_auto_update_cfg, 25);
    lv_obj_set_align(ui_auto_update_cfg, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_auto_update_cfg, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_auto_update_cfg, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_auto_update_cfg, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_auto_update_cfg, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_date_time = lv_obj_create(ui_screen_date_time);
    lv_obj_set_width(ui_date_time, 400);
    lv_obj_set_height(ui_date_time, 224);
    lv_obj_set_x(ui_date_time, 0);
    lv_obj_set_y(ui_date_time, 88);
    lv_obj_set_align(ui_date_time, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_date_time, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_date_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_zone_title = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_time_zone_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_zone_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_zone_title, 0);
    lv_obj_set_y(ui_time_zone_title, -80);
    lv_obj_set_align(ui_time_zone_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_zone_title, "Time Zone");

    ui_time_zone_num_cfg = lv_dropdown_create(ui_date_time);
    lv_dropdown_set_dir(ui_time_zone_num_cfg, LV_DIR_TOP);
    lv_dropdown_set_options(ui_time_zone_num_cfg, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12");
    lv_obj_set_width(ui_time_zone_num_cfg, 69);
    lv_obj_set_height(ui_time_zone_num_cfg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_zone_num_cfg, 150);
    lv_obj_set_y(ui_time_zone_num_cfg, -75);
    lv_obj_set_align(ui_time_zone_num_cfg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_time_zone_num_cfg, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_time_zone_num_cfg, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_zone_num_cfg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_utc_tile = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_utc_tile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_utc_tile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_utc_tile, 30);
    lv_obj_set_y(ui_utc_tile, -75);
    lv_obj_set_align(ui_utc_tile, LV_ALIGN_CENTER);
    lv_label_set_text(ui_utc_tile, "UTC");

    ui_time_zone_sign_cfg_ = lv_dropdown_create(ui_date_time);
    lv_dropdown_set_dir(ui_time_zone_sign_cfg_, LV_DIR_TOP);
    lv_dropdown_set_options(ui_time_zone_sign_cfg_, "+\n-");
    lv_obj_set_width(ui_time_zone_sign_cfg_, 50);
    lv_obj_set_height(ui_time_zone_sign_cfg_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_zone_sign_cfg_, 84);
    lv_obj_set_y(ui_time_zone_sign_cfg_, -73);
    lv_obj_set_align(ui_time_zone_sign_cfg_, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_time_zone_sign_cfg_, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_time_zone_sign_cfg_, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_zone_sign_cfg_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_daylight_title = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_daylight_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_daylight_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_daylight_title, 0);
    lv_obj_set_y(ui_daylight_title, -30);
    lv_obj_set_align(ui_daylight_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_daylight_title, "Daylight Saving Time");

    ui_daylight_cfg = lv_switch_create(ui_date_time);
    lv_obj_set_width(ui_daylight_cfg, 50);
    lv_obj_set_height(ui_daylight_cfg, 25);
    lv_obj_set_x(ui_daylight_cfg, 0);
    lv_obj_set_y(ui_daylight_cfg, -30);
    lv_obj_set_align(ui_daylight_cfg, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_daylight_cfg, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_daylight_cfg, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_daylight_cfg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_daylight_cfg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_daylight_cfg, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_daylight_cfg, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_daylight_cfg, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_manual_setting_title = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_manual_setting_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manual_setting_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manual_setting_title, 0);
    lv_obj_set_y(ui_manual_setting_title, 10);
    lv_obj_set_align(ui_manual_setting_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_manual_setting_title, "Manual Setting");

    ui_date_cfg = lv_textarea_create(ui_date_time);
    lv_obj_set_width(ui_date_cfg, 140);
    lv_obj_set_height(ui_date_cfg, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_date_cfg, 0);
    lv_obj_set_y(ui_date_cfg, 60);
    lv_obj_set_align(ui_date_cfg, LV_ALIGN_LEFT_MID);
    lv_textarea_set_max_length(ui_date_cfg, 12);
    lv_textarea_set_placeholder_text(ui_date_cfg, "01/01/2023");
    lv_textarea_set_one_line(ui_date_cfg, true);
    lv_obj_set_scrollbar_mode(ui_date_cfg, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_date_cfg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date_cfg, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_date_cfg, lv_color_hex(0x6F6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_date_cfg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_hour_cfg = lv_roller_create(ui_date_time);
    lv_roller_set_options(ui_hour_cfg,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_hour_cfg, 100);
    lv_obj_set_width(ui_hour_cfg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_hour_cfg, 40);
    lv_obj_set_y(ui_hour_cfg, 60);
    lv_obj_set_align(ui_hour_cfg, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_hour_cfg, lv_color_hex(0x4EACE4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour_cfg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_min_cfg = lv_roller_create(ui_date_time);
    lv_roller_set_options(ui_min_cfg,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_min_cfg, 100);
    lv_obj_set_width(ui_min_cfg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_min_cfg, 100);
    lv_obj_set_y(ui_min_cfg, 60);
    lv_obj_set_align(ui_min_cfg, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_min_cfg, lv_color_hex(0x4EACE4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_min_cfg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_sec_cfg = lv_roller_create(ui_date_time);
    lv_roller_set_options(ui_sec_cfg,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_sec_cfg, 100);
    lv_obj_set_width(ui_sec_cfg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sec_cfg, 160);
    lv_obj_set_y(ui_sec_cfg, 60);
    lv_obj_set_align(ui_sec_cfg, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_sec_cfg, lv_color_hex(0x4EACE4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sec_cfg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_time_label1 = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_time_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_label1, 70);
    lv_obj_set_y(ui_time_label1, 60);
    lv_obj_set_align(ui_time_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_label1, ":");

    ui_time_label2 = lv_label_create(ui_date_time);
    lv_obj_set_width(ui_time_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_label2, 130);
    lv_obj_set_y(ui_time_label2, 60);
    lv_obj_set_align(ui_time_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_label2, ":");

    lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auto_update_cfg, ui_event_auto_update_cfg, LV_EVENT_ALL, NULL);

}
