// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: sensecap

#include "../ui.h"

void ui_screen_binding_screen_init(void)
{
ui_screen_binding = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_binding, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btn_bind_back_setting = lv_btn_create(ui_screen_binding);
lv_obj_set_width( ui_btn_bind_back_setting, 100);
lv_obj_set_height( ui_btn_bind_back_setting, 50);
lv_obj_set_x( ui_btn_bind_back_setting, 10 );
lv_obj_set_y( ui_btn_bind_back_setting, 30 );
lv_obj_add_flag( ui_btn_bind_back_setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn_bind_back_setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btn_bind_back_setting, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btn_bind_back_setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btn_bind_back_setting, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_time5 = lv_label_create(ui_screen_binding);
lv_obj_set_width( ui_time5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time5, 0 );
lv_obj_set_y( ui_time5, -160 );
lv_obj_set_align( ui_time5, LV_ALIGN_CENTER );
lv_label_set_text(ui_time5,"Device Registration");
lv_obj_set_style_text_align(ui_time5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time5, &ui_font_font2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi__st_button_4 = lv_btn_create(ui_screen_binding);
lv_obj_set_width( ui_wifi__st_button_4, 60);
lv_obj_set_height( ui_wifi__st_button_4, 60);
lv_obj_set_x( ui_wifi__st_button_4, -10 );
lv_obj_set_y( ui_wifi__st_button_4, 10 );
lv_obj_set_align( ui_wifi__st_button_4, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi__st_button_4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifi__st_button_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi__st_button_4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi__st_button_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_wifi__st_button_4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wifi_st_7 = lv_img_create(ui_wifi__st_button_4);
lv_img_set_src(ui_wifi_st_7, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifi_st_7, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifi_st_7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time4 = lv_label_create(ui_screen_binding);
lv_obj_set_width( ui_time4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time4, 30 );
lv_obj_set_y( ui_time4, 20 );
lv_label_set_text(ui_time4,"00:00");
lv_obj_add_flag( ui_time4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_time4, &ui_font_font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots4 = lv_obj_create(ui_screen_binding);
lv_obj_set_width( ui_scrolldots4, 100);
lv_obj_set_height( ui_scrolldots4, 20);
lv_obj_set_x( ui_scrolldots4, 0 );
lv_obj_set_y( ui_scrolldots4, -20 );
lv_obj_set_align( ui_scrolldots4, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_scrolldots4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_scrolldots4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_scrolldots5 = lv_obj_create(ui_scrolldots4);
lv_obj_set_width( ui_scrolldots5, 7);
lv_obj_set_height( ui_scrolldots5, 7);
lv_obj_set_align( ui_scrolldots5, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_scrolldots5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots6 = lv_obj_create(ui_scrolldots4);
lv_obj_set_width( ui_scrolldots6, 7);
lv_obj_set_height( ui_scrolldots6, 7);
lv_obj_set_align( ui_scrolldots6, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_scrolldots6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scrolldots7 = lv_obj_create(ui_scrolldots4);
lv_obj_set_width( ui_scrolldots7, 7);
lv_obj_set_height( ui_scrolldots7, 7);
lv_obj_set_align( ui_scrolldots7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_scrolldots7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_scrolldots7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_scrolldots7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_scrolldots7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_scrolldots7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_user = lv_obj_create(ui_screen_binding);
lv_obj_set_width( ui_Panel_user, 400);
lv_obj_set_height( ui_Panel_user, 340);
lv_obj_set_x( ui_Panel_user, 0 );
lv_obj_set_y( ui_Panel_user, 110 );
lv_obj_set_align( ui_Panel_user, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel_user, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_user, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_user, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_user, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_user, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_SN = lv_obj_create(ui_Panel_user);
lv_obj_set_width( ui_Panel_SN, 297);
lv_obj_set_height( ui_Panel_SN, 206);
lv_obj_set_x( ui_Panel_SN, 0 );
lv_obj_set_y( ui_Panel_SN, 15 );
lv_obj_set_align( ui_Panel_SN, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel_SN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_SN = lv_label_create(ui_Panel_SN);
lv_obj_set_width( ui_Label_SN, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_SN, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_SN, 0 );
lv_obj_set_y( ui_Label_SN, 10 );
lv_label_set_text(ui_Label_SN,"S/N");

ui_TextArea_WAD = lv_textarea_create(ui_Panel_SN);
lv_obj_set_width( ui_TextArea_WAD, 220);
lv_obj_set_height( ui_TextArea_WAD, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_TextArea_WAD, 0 );
lv_obj_set_y( ui_TextArea_WAD, 120 );
lv_obj_set_align( ui_TextArea_WAD, LV_ALIGN_TOP_MID );
lv_textarea_set_max_length(ui_TextArea_WAD,1024);
lv_textarea_set_placeholder_text(ui_TextArea_WAD,"ETH  Address");
lv_textarea_set_one_line(ui_TextArea_WAD,true);
lv_obj_add_flag( ui_TextArea_WAD, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TextArea_WAD, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags
lv_obj_set_scroll_dir(ui_TextArea_WAD, LV_DIR_HOR);
lv_obj_set_style_radius(ui_TextArea_WAD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea_WAD, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea_WAD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_TextArea_WAD, lv_color_hex(0x9C9C9C), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea_WAD, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Label_WAD = lv_label_create(ui_Panel_SN);
lv_obj_set_width( ui_Label_WAD, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_WAD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_WAD, 0 );
lv_obj_set_y( ui_Label_WAD, 20 );
lv_obj_set_align( ui_Label_WAD, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_WAD,"ETH Address");

ui_TextArea_SN = lv_textarea_create(ui_Panel_SN);
lv_obj_set_width( ui_TextArea_SN, 220);
lv_obj_set_height( ui_TextArea_SN, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_TextArea_SN, 0 );
lv_obj_set_y( ui_TextArea_SN, 30 );
lv_obj_set_align( ui_TextArea_SN, LV_ALIGN_TOP_MID );
lv_textarea_set_max_length(ui_TextArea_SN,18);
lv_textarea_set_placeholder_text(ui_TextArea_SN,"Set S/N");
lv_textarea_set_one_line(ui_TextArea_SN,true);
lv_obj_clear_flag( ui_TextArea_SN, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_scroll_dir(ui_TextArea_SN, LV_DIR_HOR);
lv_obj_set_style_radius(ui_TextArea_SN, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea_SN, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea_SN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_TextArea_SN, lv_color_hex(0x9C9C9C), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea_SN, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_btn_bind = lv_btn_create(ui_Panel_user);
lv_obj_set_width( ui_btn_bind, 300);
lv_obj_set_height( ui_btn_bind, 60);
lv_obj_set_align( ui_btn_bind, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_btn_bind, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn_bind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btn_bind, lv_color_hex(0x10A37F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btn_bind, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btn_bind, lv_color_hex(0x5F6664), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_btn_bind, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_label_bind = lv_label_create(ui_btn_bind);
lv_obj_set_width( ui_label_bind, 200);
lv_obj_set_height( ui_label_bind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label_bind, LV_ALIGN_CENTER );
lv_label_set_text(ui_label_bind,"Confirm");
lv_obj_set_style_text_align(ui_label_bind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label_bind, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btn_bind_back_setting, ui_event_btn_bind_back_setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifi__st_button_4, ui_event_wifi__st_button_4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btn_bind, ui_event_btn_bind, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_binding, ui_event_screen_binding, LV_EVENT_ALL, NULL);

}
